### ISSUE TITLE
All categories button is always indented

### ISSUE THREAD

**Issue by DogmaDragon** [Lillinator/discourse-nested-categories#2]
There is no way to not indent All categories button which causes misalignment when all selected categories are not indented or the categories list ends with the one that is indented.

![image](https://github.com/user-attachments/assets/4e9e3e34-dd0f-43b6-9263-04b3d1872dd4)
![image](https://github.com/user-attachments/assets/7a317187-d532-4227-b12d-5d9cf9384745)

**Comment by Lillinator** [comment]
Can't see what you mean.  please post your issue here: https://meta.discourse.org/t/nested-sidebar-categories-or-subcategories/329437

**Comment by Lillinator** [comment]
ok i can see it now

![IMG_1972](https://github.com/user-attachments/assets/4ab34da9-ab18-4eb0-b06c-00a3cc5a74ac)

will work on a fix.  thanks!

**Comment by Lillinator** [comment]
This has been fixed.  thanks again for the bug report 👍🏼 

https://github.com/Lillinator/discourse-nested-categories/pull/3
